version: "3"

services:
  grpc-server:
    build:
      context: ./micro1
    command: air
    ports:
      - "50051:50051"
    networks:
      - reto-2
    volumes:
      - ./micro1:/app

  rabbit-server:
    build:
      context: ./micro2
    command: air
    ports:
      - "5672:5672"
    networks:
      - reto-2
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ./micro2:/app
    

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    expose:
      - 5672
    volumes:
      - ./rabbit-definitions/definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - reto-2

  gateway:
    build:
      context: ./gateway
    command: air
    ports:
      - "8080:8080"
    networks:
      - reto-2
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/ 
    volumes:
      - ./gateway:/app

networks:
  reto-2: