version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sslcerts/wildcard.crt:/jdramirezl.online.crt 
      - ./sslcerts/wildcard.key:/jdramirezl.online.key
      - ./sslcerts/wildcard.csr:/jdramirezl.online.csr 
      - ./nginx.conf:/etc/nginx/nginx.conf